---
title: "Combinando todos os resultados da extracao"
author: "Clarissa F. D. Carneiro"
date: '2022-10-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readxl)
library(writexl)
```

dados de 18-10-2022 
```{r}
Artigos.Adriano = read.csv("Article-Grid view Adriano.csv", encoding = "UTF-8")
Artigos.AnaPaula = read.csv("Article-Grid view Ana Paula.csv", encoding = "UTF-8")
Artigos.Antonio = read.csv("Article-Grid view Antonio.csv", encoding = "UTF-8")
Artigos.Clarissa = read.csv("Article-Grid view Clarissa.csv", encoding = "UTF-8")
Artigos.Giovanna = read.csv("Article-Grid view Giovanna.csv", encoding = "UTF-8")
Artigos.Giovanna = Artigos.Giovanna %>% select(-c("Fig_ID"))
Artigos.Giulia = read.csv("Article-Grid view Giulia.csv", encoding = "UTF-8")
Artigos.Glaucia = read.csv("Article-Grid view Glaucia.csv", encoding = "UTF-8")
Artigos.NathaliaF = read.csv("Article-Grid view Nathalia F.csv", encoding = "UTF-8")
Artigos.NathaliaP = read.csv("Article-Grid view Nathalia P.csv", encoding = "UTF-8")
Artigos.NathaliaP = Artigos.NathaliaP %>% select(-c("Fig_ID", "Results_ID..from.Result_ID."))
Artigos.Samantha = read.csv("Article-Grid view Samantha.csv", encoding = "UTF-8")

Figure_Table.Adriano = read.csv("Figure_Table-Grid view Adriano.csv", encoding = "UTF-8")
Figure_Table.AnaPaula = read.csv("Figure_Table-Grid view Ana Paula.csv", encoding = "UTF-8")
Figure_Table.Antonio = read.csv("Figure_Table-Grid view Antonio.csv", encoding = "UTF-8")
Figure_Table.Clarissa = read.csv("Figure_Table-Grid view Clarissa.csv", encoding = "UTF-8")
Figure_Table.Giovanna = read.csv("Figure_Table-Grid view Giovanna.csv", encoding = "UTF-8")
Figure_Table.Giulia = read.csv("Figure_Table-Grid view Giulia.csv", encoding = "UTF-8")
Figure_Table.Glaucia = read.csv("Figure_Table-Grid view Glaucia.csv", encoding = "UTF-8")
Figure_Table.NathaliaF = read.csv("Figure_Table-Grid view Nathalia F.csv", encoding = "UTF-8")
Figure_Table.NathaliaP = read.csv("Figure_Table-Grid view Nathalia P.csv", encoding = "UTF-8")
Figure_Table.Samantha = read.csv("Figure_Table-Grid view Samantha.csv", encoding = "UTF-8")

Results.Adriano = read.csv("Results-Grid view Adriano.csv", encoding = "UTF-8")
Results.AnaPaula = read.csv("Results-Grid view Ana Paula.csv", encoding = "UTF-8")
Results.Antonio = read.csv("Results-Grid view Antonio.csv", encoding = "UTF-8")
Results.Clarissa = read.csv("Results-Grid view Clarissa.csv", encoding = "UTF-8")
Results.Giovanna = read.csv("Results-Grid view Giovanna.csv", encoding = "UTF-8")
Results.Giulia = read.csv("Results-Grid view Giulia.csv", encoding = "UTF-8")
Results.Glaucia = read.csv("Results-Grid view Glaucia.csv", encoding = "UTF-8")
Results.NathaliaF = read.csv("Results-Grid view Nathalia F.csv", encoding = "UTF-8")
Results.NathaliaP = read.csv("Results-Grid view Nathalia P.csv", encoding = "UTF-8")
Results.Samantha = read.csv("Results-Grid view Samantha.csv", encoding = "UTF-8")

Protocol.Adriano = read.csv("Protocol-Grid view Adriano.csv", encoding = "UTF-8")
Protocol.AnaPaula = read.csv("Protocol-Grid view Ana Paula.csv", encoding = "UTF-8")
Protocol.Antonio = read.csv("Protocol-Grid view Antonio.csv", encoding = "UTF-8")
Protocol.Clarissa = read.csv("Protocol-Grid view Clarissa.csv", encoding = "UTF-8")
Protocol.Giovanna = read.csv("Protocol-Grid view Giovanna.csv", encoding = "UTF-8")
Protocol.Giulia = read.csv("Protocol-Grid view Giulia.csv", encoding = "UTF-8")
Protocol.Glaucia = read.csv("Protocol-Grid view Glaucia.csv", encoding = "UTF-8")
Protocol.NathaliaF = read.csv("Protocol-Grid view Nathalia F.csv", encoding = "UTF-8")
Protocol.NathaliaP = read.csv("Protocol-Grid view Nathalia P.csv", encoding = "UTF-8")
Protocol.Samantha = read.csv("Protocol-Grid view Samantha.csv", encoding = "UTF-8")

```
(esse chunk só precisa rodar em alguns computadores...)
```{r}
Artigos.Adriano = Artigos.Adriano %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.AnaPaula = Artigos.AnaPaula %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.Antonio = Artigos.Antonio %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.Clarissa = Artigos.Clarissa %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.Giovanna = Artigos.Giovanna %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.Giulia = Artigos.Giulia %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.Glaucia = Artigos.Glaucia %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.NathaliaF = Artigos.NathaliaF %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.NathaliaP = Artigos.NathaliaP %>% rename(Article_ID = X.U.FEFF.Article_ID)
Artigos.Samantha = Artigos.Samantha %>% rename(Article_ID = X.U.FEFF.Article_ID)

Figure_Table.Adriano = Figure_Table.Adriano %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.AnaPaula = Figure_Table.AnaPaula %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.Antonio = Figure_Table.Antonio %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.Clarissa = Figure_Table.Clarissa %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.Giovanna = Figure_Table.Giovanna %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.Giulia = Figure_Table.Giulia %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.Glaucia = Figure_Table.Glaucia %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.NathaliaF = Figure_Table.NathaliaF %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.NathaliaP = Figure_Table.NathaliaP %>% rename(Fig_ID = X.U.FEFF.Fig_ID)
Figure_Table.Samantha = Figure_Table.Samantha %>% rename(Fig_ID = X.U.FEFF.Fig_ID)

Results.Adriano = Results.Adriano %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.AnaPaula = Results.AnaPaula %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.Antonio = Results.Antonio %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.Clarissa = Results.Clarissa %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.Giovanna = Results.Giovanna %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.Giulia = Results.Giulia %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.Glaucia = Results.Glaucia %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.NathaliaF = Results.NathaliaF %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.NathaliaP = Results.NathaliaP %>% rename(Results_ID = X.U.FEFF.Results_ID)
Results.Samantha = Results.Samantha %>% rename(Results_ID = X.U.FEFF.Results_ID)
```
(esse daqui tem que mudar o # de lugar dependendo do computador)
```{r}
Protocol.Adriano = Protocol.Adriano %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.AnaPaula = Protocol.AnaPaula %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.Antonio = Protocol.Antonio %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.Clarissa = Protocol.Clarissa %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.Giovanna = Protocol.Giovanna %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.Giulia = Protocol.Giulia %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.Glaucia = Protocol.Glaucia %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.NathaliaF = Protocol.NathaliaF %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.NathaliaP = Protocol.NathaliaP %>% rename(Protocol = X.U.FEFF.Protocol_ID)
Protocol.Samantha = Protocol.Samantha %>% rename(Protocol = X.U.FEFF.Protocol_ID)

#Protocol.Adriano = Protocol.Adriano %>% rename(Protocol = Protocol_ID)
#Protocol.AnaPaula = Protocol.AnaPaula %>% rename(Protocol = Protocol_ID)
#Protocol.Antonio = Protocol.Antonio %>% rename(Protocol = Protocol_ID)
#Protocol.Clarissa = Protocol.Clarissa %>% rename(Protocol = Protocol_ID)
#Protocol.Giovanna = Protocol.Giovanna %>% rename(Protocol = Protocol_ID)
#Protocol.Giulia = Protocol.Giulia %>% rename(Protocol = Protocol_ID)
#Protocol.Glaucia = Protocol.Glaucia %>% rename(Protocol = Protocol_ID)
#Protocol.NathaliaF = Protocol.NathaliaF %>% rename(Protocol = Protocol_ID)
#Protocol.NathaliaP = Protocol.NathaliaP %>% rename(Protocol = Protocol_ID)
#Protocol.Samantha = Protocol.Samantha %>% rename(Protocol = Protocol_ID)
```
```{r}
Adriano = full_join(Artigos.Adriano, Figure_Table.Adriano, by = "Article_ID")
Adriano = Adriano %>% select(-c("OBS.x", "Results.x", "OBS.y", "Results.y"))
Adriano = full_join(Adriano, Results.Adriano, by = "Fig_ID")
Adriano = full_join(Adriano, Protocol.Adriano, by = "Protocol")
Adriano = Adriano %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

AnaPaula = full_join(Artigos.AnaPaula, Figure_Table.AnaPaula, by = "Article_ID")
AnaPaula = AnaPaula %>% select(-c("OBS.x", "Results.x", "OBS.y", "Results.y"))
AnaPaula = full_join(AnaPaula, Results.AnaPaula, by = "Fig_ID")
AnaPaula = full_join(AnaPaula, Protocol.AnaPaula, by = "Protocol")
AnaPaula = AnaPaula %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

Antonio = full_join(Artigos.Antonio, Figure_Table.Antonio, by = "Article_ID")
Antonio = Antonio %>% select(-c("OBS.x", "Results.x", "OBS.y", "Results.y"))
Antonio = full_join(Antonio, Results.Antonio, by = "Fig_ID")
Antonio = full_join(Antonio, Protocol.Antonio, by = "Protocol")
Antonio = Antonio %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

Clarissa = full_join(Artigos.Clarissa, Figure_Table.Clarissa, by = "Article_ID")
Clarissa = Clarissa %>% select(-c("OBS.x", "Results.x", "OBS.y", "Results.y"))
Clarissa = full_join(Clarissa, Results.Clarissa, by = "Fig_ID")
Clarissa = full_join(Clarissa, Protocol.Clarissa, by = "Protocol")
Clarissa = Clarissa %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

Giovanna = full_join(Artigos.Giovanna, Figure_Table.Giovanna, by = "Article_ID")
Giovanna = Giovanna %>% select(-c("OBS.x", "OBS.y"))
Giovanna = full_join(Giovanna, Results.Giovanna, by = "Fig_ID")
Giovanna = full_join(Giovanna, Protocol.Giovanna, by = "Protocol")
Giovanna = Giovanna %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

Giulia = full_join(Artigos.Giulia, Figure_Table.Giulia, by = "Article_ID")
Giulia = Giulia %>% select(-c("OBS.x", "Results.x", "OBS.y", "Results.y"))
Giulia = full_join(Giulia, Results.Giulia, by = "Fig_ID")
Giulia = full_join(Giulia, Protocol.Giulia, by = "Protocol")
Giulia = Giulia %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

Glaucia = full_join(Artigos.Glaucia, Figure_Table.Glaucia, by = "Article_ID")
Glaucia = Glaucia %>% select(-c("OBS.x", "Results.x", "OBS.y", "Results.y"))
Glaucia = full_join(Glaucia, Results.Glaucia, by = "Fig_ID")
Glaucia = full_join(Glaucia, Protocol.Glaucia, by = "Protocol")
Glaucia = Glaucia %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

NathaliaF = full_join(Artigos.NathaliaF, Figure_Table.NathaliaF, by = "Article_ID")
NathaliaF = NathaliaF %>% select(-c("OBS.x", "Results.x", "OBS.y", "Results.y"))
NathaliaF = full_join(NathaliaF, Results.NathaliaF, by = "Fig_ID")
NathaliaF = full_join(NathaliaF, Protocol.NathaliaF, by = "Protocol")
NathaliaF = NathaliaF %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

NathaliaP = full_join(Artigos.NathaliaP, Figure_Table.NathaliaP, by = "Article_ID")
NathaliaP = NathaliaP %>% select(-c("OBS.x", "Result_ID.x", "OBS.y", "Result_ID.y"))
NathaliaP = full_join(NathaliaP, Results.NathaliaP, by = "Fig_ID")
NathaliaP = full_join(NathaliaP, Protocol.NathaliaP, by = "Protocol")
NathaliaP = NathaliaP %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

Samantha = full_join(Artigos.Samantha, Figure_Table.Samantha, by = "Article_ID")
Samantha = Samantha %>% select(-c("OBS.x", "Results.x", "OBS.y", "Results.y"))
Samantha = full_join(Samantha, Results.Samantha, by = "Fig_ID")
Samantha = full_join(Samantha, Protocol.Samantha, by = "Protocol")
Samantha = Samantha %>% select(-c("Results_ID.y")) %>% rename(Results_ID = Results_ID.x)

```


```{r}
dados_todos = bind_rows(Adriano, AnaPaula, Antonio, Clarissa, Giovanna, Giulia, Glaucia, NathaliaF, NathaliaP, Samantha)

dados_todos = dados_todos %>% select(-c("Article_ID", "Fig_ID", "Results_ID", "Protocol", "Date_results", "Date", "Results", "Article", "Field.15", "Field.16")) %>% filter(rayyan.key!="")
```

Nesse ponto precisamos exportar a planilha para as etapas de coleta de dados com autores E limpeza de campos textuais.

```{r}
write_xlsx(dados_todos, "dados_todos.xlsx")

#apenas comparacoes que precisam de dados dos autores (media dos dois grupos, variacao no tratado, n dos dos grupos)

dados_incompletos = dados_todos %>% filter(control_mean==0|is.na(control_mean)|treated_mean==0|is.na(treated_mean)|control_n==0|is.na(control_n)|treated_n==0|is.na(treated_n)|treated_variation==0|is.na(treated_variation))
write_xlsx(dados_incompletos, "dados_incompletos_SEM_unclear_variation.xlsx")

#incluindo também "unclear variation"
dados_incompletos2 = dados_todos %>% filter(control_mean==0|is.na(control_mean)|treated_mean==0|is.na(treated_mean)|control_n==0|is.na(control_n)|treated_n==0|is.na(treated_n)|treated_variation==0|is.na(treated_variation)|variation=="Unclear"|is.na(variation))
write_xlsx(dados_incompletos2, "dados_incompletos_COM_unclear_variation.xlsx")

#incluindo também isoforma Abeta

dados_incompletos3 = dados_todos %>% filter(control_mean==0|is.na(control_mean)|treated_mean==0|is.na(treated_mean)|control_n==0|is.na(control_n)|treated_n==0|is.na(treated_n)|treated_variation==0|is.na(treated_variation)|variation=="Unclear"|is.na(variation)|Abeta_sequence=="Not informed"|is.na(Abeta_sequence)|Abeta_sequence=="not reported")
write_xlsx(dados_incompletos3, "dados_incompletos_COM_isoforma.xlsx")


```

Depois da limpeza, importamos de volta para análises.
```{r}
```
